name: KRX Prediction Server Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_IMAGE }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_IMAGE }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true

  deploy:
    needs: build
    runs-on: self-hosted
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
      DOCKER_CONTAINER: ${{ secrets.DOCKER_CONTAINER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      LOCAL_PORT: ${{ secrets.LOCAL_PORT }}
    steps:
      - name: Docker Login (on self-hosted)
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Stop and Remove Old Containers
        run: |
          sudo docker stop ${{ env.DOCKER_CONTAINER }} || true && sudo docker rm ${{ env.DOCKER_CONTAINER }} || true
          sudo docker rmi ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }} || true

      - name: Create .env
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "MONGO_NAME=${{ secrets.MONGO_NAME }}" >> .env
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
          echo "MONGO_USER=${{ secrets.MONGO_USER }}" >> .env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
      

      - name: Run Dev Container
        run: |
          sudo docker pull ${{ env.DOCKER_HUB_USERNAME}}/${{ env.DOCKER_IMAGE }}
          sudo docker run --env-file .env -d -p ${{ env.SERVER_PORT }}:${{ env.LOCAL_PORT }} --name ${{ env.DOCKER_CONTAINER }} ${{ env.DOCKER_HUB_USERNAME}}/${{ env.DOCKER_IMAGE }}